# Generated by Django 2.2.5 on 2019-10-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_waitingroom'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitingroom',
            unique_together={('room_name', 'room_id')},
        ),
    ]
