# Generated by Django 2.2.5 on 2019-11-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizz_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('room_id', models.IntegerField(unique=True)),
                ('time', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.BooleanField(default=0)),
                ('quiz_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('quizz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Player', max_length=20)),
                ('player_name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('current_question', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.WaitingRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('answer', models.BooleanField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Question')),
            ],
        ),
    ]
