# Generated by Django 2.2.5 on 2019-12-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='loghhhhhhhhhhhhhhhhhhhhhhh',
            field=models.BooleanField(default=0),
        ),
    ]
