# Generated by Django 2.2.5 on 2019-12-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_player_loghhhhhhhhhhhhhhhhhhhhhhh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='loghhhhhhhhhhhhhhhhhhhhhhh',
        ),
    ]
