# Generated by Django 2.2.5 on 2019-11-04 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_waitingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('room_id_player', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='waitingroom',
            name='quiz_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.Quiz'),
        ),
        migrations.AddField(
            model_name='waitingroom',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='room_id',
            field=models.IntegerField(unique=True),
        ),
    ]
