# Generated by Django 2.2.5 on 2019-11-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='choice',
            name='quizz_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Game.Quiz'),
        ),
    ]
