# Generated by Django 2.2.5 on 2019-11-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_auto_20191110_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='quizz_id',
        ),
    ]
