# Generated by Django 2.2.5 on 2019-11-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_remove_choice_quizz_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='room_id_player',
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.WaitingRoom'),
        ),
    ]
