# Generated by Django 2.2.5 on 2019-11-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0011_auto_20191112_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
