# Generated by Django 2.2.5 on 2019-11-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_player_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_question',
            field=models.IntegerField(default=-1),
        ),
    ]
