# Generated by Django 2.2.5 on 2019-11-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_waitingroom_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingroom',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
