# Generated by Django 2.2.5 on 2019-11-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0016_waitingroom_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
