# Generated by Django 2.2.5 on 2019-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0017_player_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
